<a href="https://colab.research.google.com/github/nastyaland/Stochastic-MaGNet/blob/Data-collection-and-Cleaning/data_collection/Nasdaq100_data_collection_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import yfinance as yf
import pandas as pd
import requests
import io

print("Fetching NASDAQ 100 component list...")
url = 'https://en.wikipedia.org/wiki/Nasdaq-100'
headers = {'User-Agent': 'Mozilla/5.0'}

try:
    response = requests.get(url, headers=headers, timeout=10)
    response.raise_for_status()
    tables = pd.read_html(io.StringIO(response.text))
    for table in tables:
        if 'Ticker' in table.columns:
            tickers = table['Ticker'].tolist()
            break
except Exception as e:
    print(f"Error fetching from Wikipedia: {e}")

tickers = [ticker.replace('.', '-') for ticker in tickers if ticker]

# yfinance's end date is exclusive
start_date = '2020-01-01'
end_date = '2025-01-01'

print(f"\nDownloading raw data for {len(tickers)} tickers...")
# auto_adjust=False ensures we obtain the underlying actual transaction price
raw_data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=False)

# Core Step: Converting data from a wide table to standard panel data format
# This transforms features (Open, High...) into columns while converting (Date, Ticker) into row indices
print("\nRestructuring data into Quant Panel format...")
df_panel = raw_data.stack(level=1, future_stack=True).swaplevel().sort_index()
df_panel.index.names = ['Ticker', 'Date']

# Retain only the 5 core fundamental features mentioned in the paper
base_features = ['Open', 'High', 'Low', 'Close', 'Volume']
df_features = df_panel[base_features]

print("\n--- Data Ready for Feature Engineering ---")
print(f"DataFrame Shape: {df_features.shape}")
print(f"Contains NaNs? {df_features.isnull().values.any()}")

# Print the header data to give you a visual sense of the structure
print("\nPeek at the formatted DataFrame:")
print(df_features.head(10))

Fetching NASDAQ 100 component list...

Downloading raw data for 101 tickers...

[*********************100%***********************]  101 of 101 completed

Restructuring data into Quant Panel format...

--- Data Ready for Feature Engineering ---
DataFrame Shape: (127058, 5)
Contains NaNs? True

Peek at the formatted DataFrame:
Price                   Open       High        Low      Close       Volume
Ticker Date
AAPL   2020-01-02  74.059998  75.150002  73.797501  75.087502  135480400.0
       2020-01-03  74.287498  75.144997  74.125000  74.357498  146322800.0
       2020-01-06  73.447502  74.989998  73.187500  74.949997  118387200.0
       2020-01-07  74.959999  75.224998  74.370003  74.597504  108872000.0
       2020-01-08  74.290001  76.110001  74.290001  75.797501  132079200.0
       2020-01-09  76.809998  77.607498  76.550003  77.407501  170108400.0
       2020-01-10  77.650002  78.167503  77.062500  77.582497  140644800.0
       2020-01-13  77.910004  79.267502  77.787498  79.239998  121532000.0
       2020-01-14  79.175003  79.392502  78.042503  78.169998  161954400.0
       2020-01-15  77.962502  78.875000  77.387497  77.834999  121923600.0

In [3]:
# This block is for mandatory cleaning the files gnerated in the directory, you shouldn't touch it if it's not necessary

# Force remove the CSV directory and all its contents
!rm -rf ./qlib_csv_data

# Force remove the binary directory if it exists
!rm -rf ./qlib_bin_data

print("Dirty directories successfully nuked! Ready for clean data.")

Dirty directories successfully nuked! Ready for clean data.

In [4]:
print("--Data Quality Check--")
valid_days_count = df_features['Close'].groupby('Ticker').count()

max_trading_days = valid_days_count.max()
print(f"Max Trading Days: {max_trading_days}\n")

#Completelt empty ticker
empty_tickers = valid_days_count[valid_days_count == 0].index.tolist()
print(f"Completely empty Tickers ({len(empty_tickers)}): {empty_tickers}\n")

#Ticker with partial missing data
incomplete_tickers = valid_days_count[(valid_days_count >0) & (valid_days_count < max_trading_days)]
print(f"\nTickers with incomplete data ({len(incomplete_tickers)}):")
for ticker,count in incomplete_tickers.items():
    missing = max_trading_days - count
    print(f" - {ticker}: Missing {missing} days (Has {count} valid days)")

clean_tickers = valid_days_count[valid_days_count == max_trading_days].index.tolist()
df_clean = df_features.loc[clean_tickers]
print("\nStripping timezone from df_clean dates...")
df_clean = df_clean.reset_index()
df_clean['Date'] = df_clean['Date'].dt.tz_localize(None)
df_clean = df_clean.set_index(['Ticker','Date'])
print("\n--- Filtering Complete ---")
print(f"Original number of tickers: {len(valid_days_count)}")
print(f"Clean number of tickers retained: {len(clean_tickers)}")
print(f"Clean DataFrame Shape: {df_clean.shape}")
print(f"Contains NaNs now? {df_clean.isnull().values.any()}")

--Data Quality Check--
Max Trading Days: 1258

Completely empty Tickers (0): []


Tickers with incomplete data (7):
 - ABNB: Missing 238 days (Has 1020 valid days)
 - APP: Missing 323 days (Has 935 valid days)
 - ARM: Missing 931 days (Has 327 valid days)
 - CEG: Missing 516 days (Has 742 valid days)
 - DASH: Missing 237 days (Has 1021 valid days)
 - GEHC: Missing 745 days (Has 513 valid days)
 - PLTR: Missing 188 days (Has 1070 valid days)

Stripping timezone from df_clean dates...

--- Filtering Complete ---
Original number of tickers: 101
Clean number of tickers retained: 94
Clean DataFrame Shape: (118252, 5)
Contains NaNs now? False

In [5]:
print(df_clean.head())
print(df_clean.tail())

Price                   Open       High        Low      Close       Volume
Ticker Date
AAPL   2020-01-02  74.059998  75.150002  73.797501  75.087502  135480400.0
       2020-01-03  74.287498  75.144997  74.125000  74.357498  146322800.0
       2020-01-06  73.447502  74.989998  73.187500  74.949997  118387200.0
       2020-01-07  74.959999  75.224998  74.370003  74.597504  108872000.0
       2020-01-08  74.290001  76.110001  74.290001  75.797501  132079200.0
Price                    Open        High         Low       Close     Volume
Ticker Date
ZS     2024-12-24  185.979996  187.589996  184.679993  187.259995   654200.0
       2024-12-26  186.000000  188.500000  185.869995  187.630005   806500.0
       2024-12-27  185.259995  185.929993  181.259995  184.559998  1256100.0
       2024-12-30  181.529999  184.404999  180.100006  183.130005  1032400.0
       2024-12-31  184.115005  184.199997  179.723007  180.410004   920800.0

In [6]:
!pip install pyqlib
import os
import pandas as pd

print("Preparing CSV files for Qlib...")

csv_dir = './qlib_csv_data'
os.makedirs(csv_dir, exist_ok = True)
df_qlib = df_clean.copy()
df_qlib.columns = [col.lower() for col in df_qlib.columns]
df_qlib = df_qlib.reset_index()
for ticker, group in df_qlib.groupby('Ticker'):
  file_path = os.path.join(csv_dir, f"{ticker}.csv")
  group.to_csv(file_path, index=False, columns=['Date','open','high','low','close','volume'])
print(f"Saved CSVs for {len(df_qlib['Ticker'].unique())} tickers in '{csv_dir}'.")

Collecting pyqlib
  Downloading pyqlib-0.9.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from pyqlib) (6.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyqlib) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from pyqlib) (2.2.2)
Collecting mlflow (from pyqlib)
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: filelock>=3.16.0 in /usr/local/lib/python3.12/dist-packages (from pyqlib) (3.25.0)
Collecting redis (from pyqlib)
  Downloading redis-7.3.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from pyqlib) (0.3.8)
Collecting fire (from pyqlib)
  Downloading fire-0.7.1-py3-none-any.whl.metadata (5.8 kB)
Collecting ruamel.yaml>=0.17.38 (from pyqlib)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Collecting python-redis-lock (from pyqlib)
  Downloading python_redis_lock-4.0.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyqlib) (4.67.3)
Collecting pymongo (from pyqlib)
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting loguru (from pyqlib)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (from pyqlib) (4.6.0)
Requirement already satisfied: gym in /usr/local/lib/python3.12/dist-packages (from pyqlib) (0.25.2)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.12/dist-packages (from pyqlib) (1.6.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from pyqlib) (1.5.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from pyqlib) (3.10.0)
Collecting jupyter (from pyqlib)
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from pyqlib) (7.17.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from pyqlib) (18.1.0)
Requirement already satisfied: pydantic-settings in /usr/local/lib/python3.12/dist-packages (from pyqlib) (2.13.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->pyqlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->pyqlib) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->pyqlib) (2025.3)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.12/dist-packages (from cvxpy->pyqlib) (1.1.1)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from cvxpy->pyqlib) (0.11.1)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.12/dist-packages (from cvxpy->pyqlib) (3.2.11)
Requirement already satisfied: scipy>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from cvxpy->pyqlib) (1.16.3)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from fire->pyqlib) (3.3.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gym->pyqlib) (3.1.2)
Requirement already satisfied: gym-notices>=0.0.4 in /usr/local/lib/python3.12/dist-packages (from gym->pyqlib) (0.1.0)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter->pyqlib) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter->pyqlib) (6.6.3)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from jupyter->pyqlib) (6.17.1)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from jupyter->pyqlib) (7.7.1)
Collecting jupyterlab (from jupyter->pyqlib)
  Downloading jupyterlab-4.5.6-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyqlib) (3.3.2)
Collecting mlflow-skinny==3.10.1 (from mlflow->pyqlib)
  Downloading mlflow_skinny-3.10.1-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.1 (from mlflow->pyqlib)
  Downloading mlflow_tracing-3.10.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow->pyqlib)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow->pyqlib) (3.1.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow->pyqlib) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow->pyqlib) (43.0.3)
Collecting docker<8,>=4.0.0 (from mlflow->pyqlib)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow->pyqlib)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<26 (from mlflow->pyqlib)
  Downloading gunicorn-25.1.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<3,>=2.5.4 (from mlflow->pyqlib)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow->pyqlib) (1.6.1)
Collecting skops<1 (from mlflow->pyqlib)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow->pyqlib) (2.0.48)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (8.3.1)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.1->mlflow->pyqlib)
  Downloading databricks_sdk-0.98.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (0.135.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (1.38.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (1.2.2)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow->pyqlib) (0.41.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->pyqlib) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (3.1.6)
Requirement already satisfied: jupyter-core>=4.7 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (5.9.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (0.10.4)
Requirement already satisfied: nbformat>=5.7 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (2.19.2)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert->pyqlib) (5.7.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings->pyqlib) (0.4.2)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo->pyqlib)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow->pyqlib) (1.3.10)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->pyqlib) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->pyqlib) (1.4.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.12/dist-packages (from clarabel>=0.5.0->cvxpy->pyqlib) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow->pyqlib) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->pyqlib) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->pyqlib) (2.2.0)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow->pyqlib) (3.1.6)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow->pyqlib)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow->pyqlib)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.7->nbconvert->pyqlib) (4.9.4)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient>=0.5.0->nbconvert->pyqlib) (7.4.9)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.7->nbconvert->pyqlib) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.7->nbconvert->pyqlib) (4.26.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from osqp>=0.6.2->cvxpy->pyqlib) (75.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow->pyqlib) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow->pyqlib) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24->pyqlib) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow->pyqlib) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow->pyqlib) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow->pyqlib) (3.3.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert->pyqlib) (2.8.3)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter->pyqlib) (6.5.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter->pyqlib) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter->pyqlib) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter->pyqlib) (3.0.16)
Requirement already satisfied: prompt-toolkit>=3.0.30 in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter->pyqlib) (3.0.52)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter->pyqlib)
  Downloading async_lru-2.2.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->pyqlib) (0.28.1)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter->pyqlib)
  Downloading jupyter_lsp-2.3.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->pyqlib) (2.14.0)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter->pyqlib)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter->pyqlib) (0.2.4)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->pyqlib) (25.1.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->pyqlib) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->pyqlib) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->pyqlib) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter->pyqlib) (1.3.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi->clarabel>=0.5.0->cvxpy->pyqlib) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow->pyqlib) (2.47.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow->pyqlib) (0.52.1)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow->pyqlib) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow->pyqlib) (4.0.12)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->pyqlib) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->pyqlib) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->pyqlib) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->pyqlib) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter->pyqlib) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow->pyqlib) (3.23.0)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel->jupyter->pyqlib)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->pyqlib) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->pyqlib) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->pyqlib) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter->pyqlib) (4.9.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert->pyqlib) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert->pyqlib) (2025.9.1)

In [7]:
# 1. Create the binary directory
!mkdir -p ./qlib_bin_data

# 2. Download the official conversion script directly from Microsoft's GitHub
!wget -qO dump_bin.py https://raw.githubusercontent.com/microsoft/qlib/main/scripts/dump_bin.py

# 3. Execute the script directly (Updated parameter name)
!python dump_bin.py dump_all --data_path ./qlib_csv_data --qlib_dir ./qlib_bin_data --date_field_name Date --symbol_field_name Ticker

2026-03-11 20:46:33.005 | INFO     | __main__:_get_all_date:307 - start get all date......
100% 94/94 [00:02<00:00, 33.72it/s]
2026-03-11 20:46:35.799 | INFO     | __main__:_get_all_date:326 - end of get all date.

2026-03-11 20:46:35.800 | INFO     | __main__:_dump_calendars:329 - start dump calendars......
2026-03-11 20:46:35.858 | INFO     | __main__:_dump_calendars:332 - end of calendars dump.

2026-03-11 20:46:35.858 | INFO     | __main__:_dump_instruments:335 - start dump instruments......
2026-03-11 20:46:35.870 | INFO     | __main__:_dump_instruments:337 - end of instruments dump.

2026-03-11 20:46:35.870 | INFO     | __main__:_dump_features:340 - start dump features......
100% 94/94 [00:03<00:00, 29.00it/s]
2026-03-11 20:46:39.112 | INFO     | __main__:_dump_features:347 - end of features dump.

In [8]:
import qlib
from qlib.config import REG_US
from qlib.contrib.data.handler import Alpha158, Alpha360
import pandas as pd

print ("Initializing Qlib environment...")
qlib.init(provider_uri = './qlib_bin_data', region = REG_US)
start_time = "2020-01-01"
end_time = "2024-12-31"

print("\nCalculating Alpha158 factors...")
handler_158 = Alpha158(instruments="all",start_time = start_time, end_time = end_time)
df_alpha158 = handler_158.fetch()

print(f"Raw shape of df_alpha158: {df_alpha158.shape}")
# Correct approach for data cleaning: First, use 'dropna(axis=1, how='all')' to remove columns like 'VWAP0' that are 100% corrupted.
# Then, use dropna() to remove the initial 60-day warm-up period, and finally take the first 5 rows.
print("\n[Real Sanity Check] Here are the actual calculated numbers:")
print(df_alpha158.dropna(axis=1, how='all').dropna().head())

print("Calculating Alpha360 factors...")
handler_360 = Alpha360(instruments="all",start_time = start_time, end_time = end_time, fit_start_time=start_time, fit_end_time=end_time)
df_alpha360 = handler_360.fetch()

print("\n-- Merging Features --")
df_clean.columns = [str(col).lower() for col in df_clean.columns]

df_clean_matched = df_clean.swaplevel().sort_index()
df_clean_matched.index.names = ['datetime', 'instrument']

#Concatenate the base features with Alpha factor sets
df_combined = pd.concat([df_clean_matched, df_alpha158, df_alpha360], axis=1)
print(f"Combined DataFrame Shape: {df_combined.shape}")

df_combined.head()

[645:MainThread](2026-03-11 20:46:42,750) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

Initializing Qlib environment...

[645:MainThread](2026-03-11 20:46:45,491) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[645:MainThread](2026-03-11 20:46:45,493) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/content/qlib_bin_data')}

Calculating Alpha158 factors...

[645:MainThread](2026-03-11 20:47:01,462) INFO - qlib.timer - [log.py:127] - Time cost: 15.967s | Loading data Done
[645:MainThread](2026-03-11 20:47:01,591) INFO - qlib.timer - [log.py:127] - Time cost: 0.039s | DropnaLabel Done
[645:MainThread](2026-03-11 20:47:03,516) INFO - qlib.timer - [log.py:127] - Time cost: 1.924s | CSZScoreNorm Done
[645:MainThread](2026-03-11 20:47:03,520) INFO - qlib.timer - [log.py:127] - Time cost: 2.056s | fit & process data Done
[645:MainThread](2026-03-11 20:47:03,524) INFO - qlib.timer - [log.py:127] - Time cost: 18.029s | Init data Done

Raw shape of df_alpha158: (118252, 159)

[Real Sanity Check] Here are the actual calculated numbers:
                           KMID      KLEN     KMID2       KUP      KUP2  \
datetime   instrument
2020-03-30 AAPL        0.016232  0.024408  0.665030  0.002832  0.116014
           ADBE        0.030755  0.048431  0.635027  0.014827  0.306149
           ADI         0.015971  0.043221  0.369509  0.005584  0.129199
           ADP         0.040937  0.051133  0.800594  0.005438  0.106350
           ADSK        0.092266  0.111321  0.828823  0.008897  0.079924

                           KLOW     KLOW2      KSFT     KSFT2     OPEN0  ...  \
datetime   instrument                                                    ...
2020-03-30 AAPL        0.005344  0.218956  0.018745  0.767972  0.984027  ...
           ADBE        0.002849  0.058824  0.018777  0.387702  0.970162  ...
           ADI         0.021666  0.501292  0.032053  0.741602  0.984281  ...
           ADP         0.004758  0.093056  0.040257  0.787301  0.960673  ...
           ADSK        0.010158  0.091253  0.093527  0.840152  0.915528  ...

                        VSUMN10   VSUMN20   VSUMN30   VSUMN60    VSUMD5  \
datetime   instrument
2020-03-30 AAPL        0.671789  0.587357  0.472653  0.493181 -0.840026
           ADBE        0.644365  0.523721  0.458107  0.474135 -0.480456
           ADI         0.754194  0.517333  0.477442  0.477891 -0.192312
           ADP         0.612578  0.518510  0.481932  0.486790 -0.857369
           ADSK        0.567633  0.470268  0.429211  0.467447  0.040860

                        VSUMD10   VSUMD20   VSUMD30   VSUMD60    LABEL0
datetime   instrument
2020-03-30 AAPL       -0.343578 -0.174715  0.054694  0.013639 -0.052617
           ADBE       -0.288730 -0.047442  0.083786  0.051730 -0.053513
           ADI        -0.508387 -0.034667  0.045116  0.044218 -0.062019
           ADP        -0.225155 -0.037020  0.036135  0.026420 -0.050922
           ADSK       -0.135267  0.059464  0.141578  0.065106 -0.108136

[5 rows x 158 columns]
Calculating Alpha360 factors...

[645:MainThread](2026-03-11 20:47:23,777) INFO - qlib.timer - [log.py:127] - Time cost: 20.019s | Loading data Done
[645:MainThread](2026-03-11 20:55:34,301) INFO - qlib.timer - [log.py:127] - Time cost: 490.323s | ProcessInf Done
/usr/local/lib/python3.12/dist-packages/qlib/data/dataset/processor.py:241: RuntimeWarning: Mean of empty slice
  self.mean_train = np.nanmean(df[cols].values, axis=0)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_nanfunctions_impl.py:2035: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
[645:MainThread](2026-03-11 20:55:35,599) INFO - qlib.timer - [log.py:127] - Time cost: 1.294s | ZScoreNorm Done
[645:MainThread](2026-03-11 20:55:36,252) INFO - qlib.timer - [log.py:127] - Time cost: 0.650s | Fillna Done
[645:MainThread](2026-03-11 20:55:36,395) INFO - qlib.timer - [log.py:127] - Time cost: 0.070s | DropnaLabel Done
[645:MainThread](2026-03-11 20:55:38,063) INFO - qlib.timer - [log.py:127] - Time cost: 1.666s | CSZScoreNorm Done
[645:MainThread](2026-03-11 20:55:38,066) INFO - qlib.timer - [log.py:127] - Time cost: 494.287s | fit & process data Done
[645:MainThread](2026-03-11 20:55:38,070) INFO - qlib.timer - [log.py:127] - Time cost: 514.312s | Init data Done

-- Merging Features --
Combined DataFrame Shape: (118252, 525)

                             open        high         low       close  \
datetime   instrument
2020-01-02 AAPL         74.059998   75.150002   73.797501   75.087502
           ADBE        330.000000  334.480011  329.170013  334.429993
           ADI         120.110001  120.650002  118.739998  120.430000
           ADP         171.960007  172.000000  169.199997  170.320007
           ADSK        184.210007  187.889999  181.880005  187.830002

                            volume      KMID      KLEN     KMID2       KUP  \
datetime   instrument
2020-01-02 AAPL        135480400.0  0.013874  0.018262  0.759707  0.000844
           ADBE          1990100.0  0.013424  0.016091  0.834274  0.000152
           ADI           1279300.0  0.002664  0.015902  0.167539  0.001832
           ADP           1364600.0 -0.009537  0.016283 -0.585713  0.000233
           ADSK          1515000.0  0.019651  0.032626  0.602329  0.000326

                           KUP2  ...  VOLUME8  VOLUME7  VOLUME6  VOLUME5  \
datetime   instrument            ...
2020-01-02 AAPL        0.046211  ...      0.0      0.0      0.0      0.0
           ADBE        0.009420  ...      0.0      0.0      0.0      0.0
           ADI         0.115184  ...      0.0      0.0      0.0      0.0
           ADP         0.014283  ...      0.0      0.0      0.0      0.0
           ADSK        0.009983  ...      0.0      0.0      0.0      0.0

                       VOLUME4  VOLUME3  VOLUME2  VOLUME1   VOLUME0    LABEL0
datetime   instrument
2020-01-02 AAPL            0.0      0.0      0.0      0.0  0.085742  0.270136
           ADBE            0.0      0.0      0.0      0.0  0.085742  0.184407
           ADI             0.0      0.0      0.0      0.0  0.085742 -0.483767
           ADP             0.0      0.0      0.0      0.0  0.085742  0.017206
           ADSK            0.0      0.0      0.0      0.0  0.085742  0.414086

[5 rows x 525 columns]

In [9]:
print(df_alpha158.head())
print(df_alpha360.tail())

                           KMID      KLEN     KMID2       KUP      KUP2  \
datetime   instrument
2020-01-02 AAPL        0.013874  0.018262  0.759707  0.000844  0.046211
           ADBE        0.013424  0.016091  0.834274  0.000152  0.009420
           ADI         0.002664  0.015902  0.167539  0.001832  0.115184
           ADP        -0.009537  0.016283 -0.585713  0.000233  0.014283
           ADSK        0.019651  0.032626  0.602329  0.000326  0.009983

                           KLOW     KLOW2      KSFT     KSFT2     OPEN0  ...  \
datetime   instrument                                                    ...
2020-01-02 AAPL        0.003544  0.194083  0.016574  0.907579  0.986316  ...
           ADBE        0.002515  0.156306  0.015788  0.981161  0.986754  ...
           ADI         0.011406  0.717278  0.012239  0.769633  0.997343  ...
           ADP         0.006513  0.400003 -0.003256 -0.199993  1.009629  ...
           ADSK        0.012649  0.387688  0.031974  0.980034  0.980727  ...

                       VSUMN10  VSUMN20  VSUMN30  VSUMN60  VSUMD5  VSUMD10  \
datetime   instrument
2020-01-02 AAPL            NaN      NaN      NaN      NaN     NaN      NaN
           ADBE            NaN      NaN      NaN      NaN     NaN      NaN
           ADI             NaN      NaN      NaN      NaN     NaN      NaN
           ADP             NaN      NaN      NaN      NaN     NaN      NaN
           ADSK            NaN      NaN      NaN      NaN     NaN      NaN

                       VSUMD20  VSUMD30  VSUMD60    LABEL0
datetime   instrument
2020-01-02 AAPL            NaN      NaN      NaN  0.007968
           ADBE            NaN      NaN      NaN  0.005726
           ADI             NaN      NaN      NaN -0.011749
           ADP             NaN      NaN      NaN  0.001353
           ADSK            NaN      NaN      NaN  0.011733

[5 rows x 159 columns]
                        CLOSE59   CLOSE58   CLOSE57   CLOSE56   CLOSE55  \
datetime   instrument
2024-12-31 WDAY       -0.365745 -0.284489 -0.261207 -0.169912 -0.268151
           WDC         0.751821  0.728557  0.570976  0.530592  0.608000
           WMT        -0.571284 -0.540167 -0.503945 -0.559665 -0.535143
           XEL        -0.251367 -0.262456 -0.296420 -0.336596 -0.329280
           ZS         -0.135531  0.009151  0.287364  0.584367  0.669831

                        CLOSE54   CLOSE53   CLOSE52   CLOSE51   CLOSE50  ...  \
datetime   instrument                                                    ...
2024-12-31 WDAY       -0.238426 -0.190684 -0.297262 -0.234029 -0.211896  ...
           WDC         0.792930  0.803927  0.882083  0.840120  0.809582  ...
           WMT        -0.529191 -0.448813 -0.480742 -0.507368 -0.486868  ...
           XEL        -0.274565 -0.244544 -0.199654 -0.268773 -0.203699  ...
           ZS          0.620730  0.569456  0.451885  0.361464  0.399592  ...

                        VOLUME8   VOLUME7   VOLUME6   VOLUME5   VOLUME4  \
datetime   instrument
2024-12-31 WDAY       -0.010344 -0.008854 -0.009429 -0.008477 -0.012348
           WDC        -0.010344 -0.008854 -0.009429 -0.008477 -0.012348
           WMT        -0.010344 -0.008854 -0.009429 -0.008477 -0.012348
           XEL        -0.010344 -0.008854 -0.009429 -0.008477 -0.012348
           ZS         -0.010344 -0.008854 -0.009429 -0.008477 -0.012348

                        VOLUME3   VOLUME2   VOLUME1   VOLUME0  LABEL0
datetime   instrument
2024-12-31 WDAY       -0.010111 -0.009694 -0.008475  0.085742     0.0
           WDC        -0.010111 -0.009694 -0.008475  0.085742     0.0
           WMT        -0.010111 -0.009694 -0.008475  0.085742     0.0
           XEL        -0.010111 -0.009694 -0.008475  0.085742     0.0
           ZS         -0.010111 -0.009694 -0.008475  0.085742     0.0

[5 rows x 361 columns]

In [10]:
rows_with_nan = df_combined.isnull().any(axis=1).sum()
total_rows = len(df_combined)
print(f"Total rows before cleaning: {total_rows}")
print(f"Rows containing at least one NaN: {rows_with_nan}")
print(f"Percentage of rows to be dropped: {(rows_with_nan/total_rows)*100:.2f}%\n")

print("Top 20 features with the most NaNs:")
nan_counts = df_combined.isnull().sum().sort_values(ascending=False)
print(nan_counts.head(20))
print("\nPeek at the rows with NaNs (Notice the dates):")
rows_with_nan_df = df_combined[df_combined.isnull().any(axis=1)]
print(rows_with_nan_df.head(10))

Total rows before cleaning: 118252
Rows containing at least one NaN: 118252
Percentage of rows to be dropped: 100.00%

Top 20 features with the most NaNs:
VWAP0     118252
ROC60       5640
ROC30       2820
ROC20       1880
CORD5       1149
CORD10      1033
ROC10        940
CORD20       852
CORD30       732
CORR5        692
RSQR5        691
CORD60       525
ROC5         470
CORR10       416
RSQR10       415
WVMA60       188
WVMA30       188
WVMA5        188
WVMA10       188
LABEL0       188
dtype: int64

Peek at the rows with NaNs (Notice the dates):
                             open        high         low       close  \
datetime   instrument
2020-01-02 AAPL         74.059998   75.150002   73.797501   75.087502
           ADBE        330.000000  334.480011  329.170013  334.429993
           ADI         120.110001  120.650002  118.739998  120.430000
           ADP         171.960007  172.000000  169.199997  170.320007
           ADSK        184.210007  187.889999  181.880005  187.830002
           AEP          94.500000   94.559998   92.980003   93.459999
           ALNY        115.570000  117.599998  114.010002  115.620003
           AMAT         62.000000   62.650002   61.700001   62.200001
           AMD          46.860001   49.250000   46.630001   49.099998
           AMGN        243.000000  243.190002  238.979996  240.100006

                            volume      KMID      KLEN     KMID2       KUP  \
datetime   instrument
2020-01-02 AAPL        135480400.0  0.013874  0.018262  0.759707  0.000844
           ADBE          1990100.0  0.013424  0.016091  0.834274  0.000152
           ADI           1279300.0  0.002664  0.015902  0.167539  0.001832
           ADP           1364600.0 -0.009537  0.016283 -0.585713  0.000233
           ADSK          1515000.0  0.019651  0.032626  0.602329  0.000326
           AEP           1779700.0 -0.011005  0.016720 -0.658231  0.000635
           ALNY           593500.0  0.000433  0.031063  0.013928  0.017132
           AMAT          6647900.0  0.003226  0.015323  0.210527  0.007258
           AMD          80331100.0  0.047802  0.055911  0.854961  0.003201
           AMGN          2088000.0 -0.011934  0.017325 -0.688834  0.000782

                           KUP2  ...  VOLUME8  VOLUME7  VOLUME6  VOLUME5  \
datetime   instrument            ...
2020-01-02 AAPL        0.046211  ...      0.0      0.0      0.0      0.0
           ADBE        0.009420  ...      0.0      0.0      0.0      0.0
           ADI         0.115184  ...      0.0      0.0      0.0      0.0
           ADP         0.014283  ...      0.0      0.0      0.0      0.0
           ADSK        0.009983  ...      0.0      0.0      0.0      0.0
           AEP         0.037973  ...      0.0      0.0      0.0      0.0
           ALNY        0.551531  ...      0.0      0.0      0.0      0.0
           AMAT        0.473685  ...      0.0      0.0      0.0      0.0
           AMD         0.057253  ...      0.0      0.0      0.0      0.0
           AMGN        0.045131  ...      0.0      0.0      0.0      0.0

                       VOLUME4  VOLUME3  VOLUME2  VOLUME1   VOLUME0    LABEL0
datetime   instrument
2020-01-02 AAPL            0.0      0.0      0.0      0.0  0.085742  0.270136
           ADBE            0.0      0.0      0.0      0.0  0.085742  0.184407
           ADI             0.0      0.0      0.0      0.0  0.085742 -0.483767
           ADP             0.0      0.0      0.0      0.0  0.085742  0.017206
           ADSK            0.0      0.0      0.0      0.0  0.085742  0.414086
           AEP             0.0      0.0      0.0      0.0  0.085742  0.092424
           ALNY            0.0      0.0      0.0      0.0  0.085742  0.061320
           AMAT            0.0      0.0      0.0      0.0  0.085742 -0.859105
           AMD             0.0      0.0      0.0      0.0  0.085742 -0.199755
           AMGN            0.0      0.0      0.0      0.0  0.085742  0.258887

[10 rows x 525 columns]

In [11]:
threshold = len(df_combined) * 0.9
df_filtered_cols = df_combined.dropna(axis=1, thresh = threshold)

df_final = df_filtered_cols.dropna()
print(f"Final Cleaned Shape: {df_final.shape}")
print(f"Total Stocks: {len(df_final.index.get_level_values('instrument').unique())}")
print(f"Total Trading Days: {len(df_final.index.get_level_values('datetime').unique())}")

Final Cleaned Shape: (111507, 524)
Total Stocks: 94
Total Trading Days: 1196

In [12]:
days_per_stock = df_final.groupby('instrument').size()
target_days = days_per_stock.max()
good_stocks = days_per_stock[days_per_stock == target_days].index.tolist()
bad_stocks = days_per_stock[days_per_stock < target_days].index.tolist()

print(f"Standard trading days: {target_days}")
print(f"Perfectly matched stocks: {len(good_stocks)}")
print(f"Stocks need to be removed: {bad_stocks}")
df_perfect = df_final.loc[slice(None), good_stocks, :]

print(df_perfect.head())
print(df_perfect.tail())

Standard trading days: 1196
Perfectly matched stocks: 93
Stocks need to be removed: ['FER']
                             open        high         low       close  \
datetime   instrument
2020-03-30 AAPL         62.685001   63.880001   62.349998   63.702499
           ADBE        308.890015  322.970001  308.010010  318.390015
           ADI          89.540001   91.470001   87.599998   90.970001
           ADP         132.399994  138.539993  131.770004  137.820007
           ADSK        142.740005  157.179993  141.289993  155.910004

                            volume      KMID      KLEN     KMID2       KUP  \
datetime   instrument
2020-03-30 AAPL        167976400.0  0.016232  0.024408  0.665030  0.002832
           ADBE          4340200.0  0.030755  0.048431  0.635027  0.014827
           ADI           3268200.0  0.015971  0.043221  0.369509  0.005584
           ADP           2522300.0  0.040937  0.051133  0.800594  0.005438
           ADSK          3378400.0  0.092266  0.111321  0.828823  0.008897

                           KUP2  ...   VOLUME8   VOLUME7   VOLUME6   VOLUME5  \
datetime   instrument            ...
2020-03-30 AAPL        0.116014  ... -0.010344 -0.008854 -0.009429 -0.008477
           ADBE        0.306149  ... -0.010344 -0.008854 -0.009429 -0.008477
           ADI         0.129199  ... -0.010344 -0.008854 -0.009429 -0.008477
           ADP         0.106350  ... -0.010344 -0.008854 -0.009429 -0.008477
           ADSK        0.079924  ... -0.010344 -0.008854 -0.009429 -0.008477

                        VOLUME4   VOLUME3   VOLUME2   VOLUME1   VOLUME0  \
datetime   instrument
2020-03-30 AAPL       -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           ADBE       -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           ADI        -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           ADP        -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           ADSK       -0.012348 -0.010111 -0.009694 -0.008475  0.085742

                         LABEL0
datetime   instrument
2020-03-30 AAPL       -2.046417
           ADBE       -2.080675
           ADI        -2.405911
           ADP        -1.981596
           ADSK       -4.169245

[5 rows x 524 columns]
                             open        high         low       close  \
datetime   instrument
2024-12-27 WDAY        267.600006  268.359985  263.269989  266.239990
           WDC          46.386997   46.568405   45.653816   45.880573
           WMT          92.129997   92.349998   91.029999   91.660004
           XEL          67.720001   68.650002   67.610001   68.139999
           ZS          185.259995  185.929993  181.259995  184.559998

                           volume      KMID      KLEN     KMID2       KUP  \
datetime   instrument
2024-12-27 WDAY         1602800.0 -0.005082  0.019021 -0.267194  0.002840
           WDC          5506061.0 -0.010917  0.019716 -0.553718  0.003911
           WMT         11384400.0 -0.005101  0.014328 -0.356056  0.002388
           XEL          2015000.0  0.006202  0.015357  0.403844  0.007531
           ZS           1256100.0 -0.003778  0.025208 -0.149892  0.003617

                           KUP2  ...   VOLUME8   VOLUME7   VOLUME6   VOLUME5  \
datetime   instrument            ...
2024-12-27 WDAY        0.149308  ... -0.010344 -0.008854 -0.009429 -0.008477
           WDC         0.198349  ... -0.010344 -0.008854 -0.009429 -0.008477
           WMT         0.166668  ... -0.010344 -0.008854 -0.009429 -0.008477
           XEL         0.490386  ... -0.010344 -0.008854 -0.009429 -0.008477
           ZS          0.143469  ... -0.010344 -0.008854 -0.009429 -0.008477

                        VOLUME4   VOLUME3   VOLUME2   VOLUME1   VOLUME0  \
datetime   instrument
2024-12-27 WDAY       -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           WDC        -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           WMT        -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           XEL        -0.012348 -0.010111 -0.009694 -0.008475  0.085742
           ZS         -0.012348 -0.010111 -0.009694 -0.008475  0.085742

                         LABEL0
datetime   instrument
2024-12-27 WDAY       -0.613919
           WDC        -0.028124
           WMT        -0.127416
           XEL        -0.074136
           ZS         -0.602453

[5 rows x 524 columns]

In [13]:
print(df_perfect.shape)

(111228, 524)

In [14]:
# From Dataset.py the dimension of the tensor should be (N * T * F) (Stock, Timesteps. Features)
import torch
import numpy as np

cols = df_perfect.columns.tolist()
if 'close' in cols:
  cols.insert(0, cols.pop(cols.index('close')))
df_ready = df_perfect[cols]

df_ready = df_ready.sort_index(level = ['instrument', 'datetime'])

n_stocks = 93
n_features = 532
days_per_stock = df_ready.groupby('instrument').size()
min_days = days_per_stock.min()
print(f"Minimum trading days across all stocks: {min_days}")
df_cube = df_ready.groupby('instrument').tail(min_days)
df_cube.head()

Minimum trading days across all stocks: 1196

,,close,open,high,low,volume,KMID,KLEN,KMID2,KUP,KUP2,...,VOLUME7,VOLUME6,VOLUME5,VOLUME4,VOLUME3,VOLUME2,VOLUME1,VOLUME0,LABEL0,LABEL0
datetime,instrument,,,,,,,,,,,,,,,,,,,,,
2020-03-30,AAPL,63.702499,62.685001,63.880001,62.349998,167976400.0,0.016232,0.024408,0.665030,0.002832,0.116014,...,-0.008854,-0.009429,-0.008477,-0.012348,-0.010111,-0.009694,-0.008475,0.085742,-0.052617,-2.046417
2020-03-31,AAPL,63.572498,63.900002,65.622498,63.000000,197002000.0,-0.005125,0.041041,-0.124882,0.026956,0.656815,...,-0.008854,-0.009429,-0.008477,-0.012348,-0.010111,-0.009694,-0.008475,0.085742,0.016687,0.603499
2020-04-01,AAPL,60.227501,61.625000,62.180000,59.782501,176218400.0,-0.022677,0.038905,-0.582899,0.009006,0.231491,...,-0.008854,-0.009429,-0.008477,-0.012348,-0.010111,-0.009694,-0.008475,0.085742,-0.014371,-0.584046
2020-04-02,AAPL,61.232498,60.084999,61.287498,59.224998,165934000.0,0.019098,0.034326,0.556363,0.000915,0.026667,...,-0.008854,-0.009429,-0.008477,-0.012348,-0.010111,-0.009694,-0.008475,0.085742,0.087237,3.301096
2020-04-03,AAPL,60.352501,60.700001,61.424999,59.742500,129880000.0,-0.005725,0.027718,-0.206538,0.011944,0.430906,...,-0.008854,-0.009429,-0.008477,-0.012348,-0.010111,-0.009694,-0.008475,0.085742,-0.011582,-0.477402

In [15]:
data_3d = df_cube.values.reshape(n_stocks, min_days, n_features)
data_tensor = torch.from_numpy(data_3d).float()
print(f"Formatted Data Shape: {data_tensor.shape}")
torch.save(data_tensor, 'my_nas100_2025_data.pt')

Formatted Data Shape: torch.Size([93, 1196, 532])

In [1]:
# Upload all MaGNet model training files and run the command below to train

!python train.py

python3: can't open file '/content/train.py': [Errno 2] No such file or directory